### ISSUE TITLE
Simply Doesnt Work !!

### ISSUE THREAD

**Issue by gmonk** [DT42/BerryNet#10]
Nothing actually works :-1:   Followed directions and the dashboard doesnt show anything.  looking at the directory I can see there are serveral snapshots but thery are all the same image with different time stamps

**Comment by bafu** [comment]
@gmonk Thanks for the issue report. Can you share your `/var/log/syslog` with me and I will check this issue? Thanks.

**Comment by GitHubForNH2** [comment]
i also meet the same problem and this is my syslog file:
[syslog.zip](https://github.com/DT42/BerryNet/files/1523839/syslog.zip)

**Comment by bafu** [comment]
@GitHubForNH2 In your syslog, I found the error message `Error: listen EADDRINUSE :::1883`, which means that BerryNet MQTT broker's default port has been registered by another service, e.g. mosquitto MQTT server.

In this case, there are two ways to resolve this issue:

1. Disable mosquitto MQTT server by `sudo service mosquitto stop`.
1. Change BerryNet MQTT broker's default port in broker.js.

and then restart BerryNet.

I will close this issue and please free to re-open it if this issue can not be resolved, thanks.
