### ISSUE TITLE
About reading the log

### ISSUE THREAD

**Issue by yimingliu0216** [DT42/BerryNet#19]
I used berrynet-manager log to view the log.  However, after awhile, the log is too long to read.

I want to know how to clean the log, how to use tail -f to read the log?

Thanks.

**Comment by bafu** [comment]
@yimingliu0216 We are designing a new log mechanism. Before it is available, you can use these methods to check logs:

```
# Show the latest 30 log messages
$ berrynet-manager log | tail -n 30

# Display and save log simultaneously
$ berrynet-manager log | tee berrynet-manager.log
```
