### ISSUE TITLE
MQTT service not work 

### ISSUE THREAD

**Issue by yimingliu0216** [DT42/BerryNet#20]
Hi,

I installed Mosquitto broker and run it locally. However, the berrynet-manager log still gives me following error: 
Jan 17 17:51:41 raspberrypi node[21074]: /usr/local/berrynet/node_modules/@line/bot-sdk/dist/client.js:9
Jan 17 17:51:41 raspberrypi node[21074]:             throw new Error("no channel access token");
Jan 17 17:51:41 raspberrypi node[21074]:             ^
Jan 17 17:51:41 raspberrypi node[21074]: Error: no channel access token
Jan 17 17:51:41 raspberrypi node[21074]:     at new Client (/usr/local/berrynet/node_modules/@line/bot-sdk/dist/client.js:9:19)
Jan 17 17:51:41 raspberrypi node[21074]:     at Object.<anonymous> (/usr/local/berrynet/line.js:39:20)
Jan 17 17:51:41 raspberrypi node[21074]:     at Module._compile (module.js:571:32)
Jan 17 17:51:41 raspberrypi node[21074]:     at Object.Module._extensions..js (module.js:580:10)
Jan 17 17:51:41 raspberrypi node[21074]:     at Module.load (module.js:488:32)
Jan 17 17:51:41 raspberrypi node[21074]:     at tryModuleLoad (module.js:447:12)
Jan 17 17:51:41 raspberrypi node[21074]:     at Function.Module._load (module.js:439:3)
Jan 17 17:51:41 raspberrypi node[21074]:     at Module.runMain (module.js:605:10)
Jan 17 17:51:41 raspberrypi node[21074]:     at run (bootstrap_node.js:427:7)
Jan 17 17:51:41 raspberrypi node[21074]:     at startup (bootstrap_node.js:151:9)
Jan 17 17:51:41 raspberrypi systemd[1]: line.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 17:51:41 raspberrypi systemd[1]: line.service: Unit entered failed state.
pi@raspberrypi:~ $ pberrypi systemd[1]: line.service: Failed with result 'exit-code'.

**Comment by bafu** [comment]
@yimingliu0216 The error log is related to LINE client instead of mosquitto.

If you can not run Mosquitto successfully, it might be that BerryNet's default MQTT broker, Mosca, was running and consumed MQTT broker's default port number.

You can stop Mosca and launch Mosquitto manually to see if it works.
