### ISSUE TITLE
N: See apt-secure(8) manpage for repository creation and user configuration details.

### ISSUE THREAD

**Issue by Tondy** [DT42/BerryNet#23]
Hello

I need some help as I am receiving the error below every time I am running sudo apt-get update. 
Please help

W: GPG error: https://raw.githubusercontent.com/DT42/BerryNet-repo/master stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A3211A87D7ACFE23
E: The repository 'https://raw.githubusercontent.com/DT42/BerryNet-repo/master stretch InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by tuansacer** [comment]
I'm have the same error :(

**Comment by bafu** [comment]
@Tondy @tuansacer Sorry for hitting the issue because you find the easter egg!

We're working on Python-based BerryNet which has not been announced yet.

To resolve this issue, please use this command below:

```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A3211A87D7ACFE23
$ sudo apt update
```

**Comment by bafu** [comment]
This issue has been fixed in v2.3.0.

**Comment by hemendram0** [comment]
i am facing same problem. help me

**Comment by muketot** [comment]
Pls help me

**Comment by bandarikanth** [comment]
remove sources .list and index.html in /etc/apt dir

# cp /etc/apt/preferences.d/index.html /tmp
# rm -rf /etc/apt/preferences.d/index.html
#cp /etc/apt/sources.list  /tmp
# rm -rf sources.list

     then reboot

**Comment by PrinsZuko** [comment]
> @Tondy @tuansacer Sorry for hitting the issue because you find the easter egg!
> 
> We're working on Python-based BerryNet which has not been announced yet.
> 
> To resolve this issue, please use this command below:
> 
> ```
> $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A3211A87D7ACFE23
> $ sudo apt update
> ```
> 
> I will keep this issue open until Python-based BerryNet is announced officially.

Each time I try these type of fixes it just says "command not found" in debian 9.5

**Comment by grandpaul** [comment]
Hi PrinsZuko, 

Can you check if sudo is installed? apt-key and apt must be run as root. 
If your system admin doesn't install "sudo" package, please install it first.
