### ISSUE TITLE
IP camera access to user name and password

### ISSUE THREAD

**Issue by ytgcljj** [DT42/BerryNet#3]
IP camera access to user name and password，I don't know how to set it up

**Comment by bafu** [comment]
@ytgcljj The way to feed username and password info depends on your camera. If your camera is in the [camera connection database](https://www.ispyconnect.com/sources.aspx), you can try the generated link.

If your camera is not in the database, you can check the camera's user manual, or contact the vendor for the access details.

**Comment by bafu** [comment]
If this issue still exists, please feel free to reopen this issue.

**Comment by ytgcljj** [comment]
thank you ,let me try

**Comment by kouchla** [comment]
@bafu: In which file should I configure my IP cam (config,js or camera.js or other file) I kowon how  to feed username and password with my camera but I don,t know in which BerryNnet's file

Thank's with you help

**Comment by ytgcljj** [comment]
@kouchla  can you tell me how to set up the ip camera with username and password? 
  i visited the camera ip http://192.168.254.4/doc/page/login.asp?_1495505377878

**Comment by kouchla** [comment]
@ytgcljj  With my VLC player, I can see the flow of the camera (DLink) by doing this:
http://username:password@ipcanera address:port/video.cgi

With Foscam cameras, replace video.cgi with videostream.cgi (I think).

I hope it helps.
