### ISSUE TITLE
Add Video/ Live Stream Analysis

### ISSUE THREAD

**Issue by hskang9** [DT42/BerryNet#4]
Is Berrynet able to detect objects in video or while streaming? Even though fps may be lower because of the hardware, it would work on other IoT device specialized in computer vision(Nvidia Jetson, Intel Joule, etc).

**Comment by bafu** [comment]
@hskang9 Yes, this feature is in the project roadmap. I totally agree with you that this feature will be useful if BerryNet runs on a more powerful HW platform, or the real-time demand is not very strong in a scenario.

**Comment by YingHou** [comment]
Hi Bafu, I was wondering what's the timeline to add this feature in?

**Comment by bafu** [comment]
@hskang9 @YingHou Video streaming support is available in 2.1.0. Please try the new feature and any suggestions is welcome, thanks!
