### ISSUE TITLE
 the IP camera access the user name and password

### ISSUE THREAD

**Issue by ytgcljj** [DT42/BerryNet#5]
I would like to ask if the IP camera access the user name and password, how to modify the configuration?

**Comment by bafu** [comment]
Hi @ytgcljj, is [my previous comment](https://github.com/DT42/BerryNet/issues/3#issuecomment-302863874) useful for you?

**Comment by ytgcljj** [comment]
thank you

**Comment by ytgcljj** [comment]
Hi @bafu  If i want to change the usb camera,how to change?

**Comment by bafu** [comment]
To use USB camera as input source, you need to extend the `camera.js` to get snapshots from the USB camera, or write another MQTT client by leveraging `camera.js`' MQTT-related codes.

**Comment by bafu** [comment]
USB camera has been supported in 2.1.0. Please try the new feature and any suggestions is welcome.
