### ISSUE TITLE
frame rate on 1080HD?

### ISSUE THREAD

**Issue by smajida** [DT42/BerryNet#7]
Hi,

I was wondering how fast is  BerryNet on 1080HD.

**Comment by wliu2016** [comment]
Based on my testing results, if testing a picture from pi camera v2 module at 1080p, it cost around 3 seconds to process the picture.  

Bofu also mentioned the other day that the new release will reduce the processing time to ~1.3 seconds. 

Hope it helps.

**Comment by smajida** [comment]
yeah it helps. thanks.
